### ISSUE TITLE
Please update the readme to install and run the repo

### ISSUE THREAD

**Issue by kalyanipullela** [Salmandabbakuti/blockTrack#7]
Hello @Salmandabbakuti

Thanks for the blogs and the repo link.
It will help developers like me to start the fabric NodeJS chaincodes. 
So, could you please update the Readme for this repo, by which the code can be executed without any failures.

Thank you

**Comment by Salmandabbakuti** [comment]
Hello @kalyanipullela 

Thanks for your response. I just updated Readme. have a look at it and ping me if you are facing any errors. btw, the entire application is deployed [here](https://bcdevs.github.io/blockTrack-cloud/) using cloud services. try it and I hope it will help you understand how end to end applications look like in blockchain.
