### ISSUE TITLE
How to get the list of transactionIDs

### ISSUE THREAD

**Issue by pgulp9981** [Salmandabbakuti/blockTrack#8]
Hey @Salmandabbakuti,

Your repo is quite interesting to learn Fabric.
So how can we get the list of transactions ids their block details from the Nodejs SDKs.
Have you ever tried doing it so?
If yes, then how's it's possible to start off with

Awaiting for your response

Thanks

**Comment by Salmandabbakuti** [comment]
Hello @pgulp9981 ,
 
in order to get all the network information including transaction data, the best option is to  connect hyperledger explorer to your network. it's very good tool to get all network statistics. you can also get transaction info using fabric-client module of Node SDK. have a look at methods in fabric-client module documentation [https://fabric-sdk-node.github.io/release-1.4/Channel.html#queryTransaction](here).

**Comment by pgulp9981** [comment]
> [https://fabric-sdk-node.github.io/release-1.4/Channel.html#queryTransaction](here).

Hey @Salmandabbakuti 

Thanks for the info.
But using the fabric client module, we have to specify the transaction ID, but I want to get those transaction IDs as a whole.

**Comment by Salmandabbakuti** [comment]
@pgulp9981,
So hyperledger explorer is the only choice here.

**Comment by pgulp9981** [comment]
> @pgulp9981,
> So hyperledger explorer is the only choice here.

Okay Thank you

**Comment by pgulp9981** [comment]
Hello@Salmandabbakuti 

Just a casual question
The implementation of Fabric using Nodejs in Fabcar example and balance-transfer example is different. Both uses the fabric network and deploys a chaincode.
You have used the code i.e similar to Fabcar example
Working is same but the coding implementation is different
What's the main difference in Nodejs Fabcar example and balance-transfer example

Any help is appreciated

Thank you

**Comment by Salmandabbakuti** [comment]
Hey @pgulp9981,

Are you talking about chaincode implementation of both the samples or API implementation of Client Application??

**Comment by pgulp9981** [comment]
@Salmandabbakuti 

Thank you for your response

Both the chaincode samples and API implementation
When I have evaluated the code, both the examples are written in a different way and the API is also different.
Could you help me what's the difference in both of them and which method should be used?

**Comment by Salmandabbakuti** [comment]
The difference is in chaincode API  and client side API interaction. highlevel API and low level APIs. Better use high level API

**Comment by pgulp9981** [comment]
Thank you, Salman,
So for the client API, you have used the fabric-network APIs and in balance-transfer, they used the fabric-client API.
So which should be used? Fabric-network API or Fabric-client API?
What's the difference between them and how can we choose which should be used?

**Comment by Salmandabbakuti** [comment]
Hey @pgulp9981,
It would take forever to talk all those things here. Lets have a talk on mail or Whatsapp. Surely I will help..

**Comment by pgulp9981** [comment]
Thank you @ Salman

Sure, will have a talk in the mail.
